// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/sendme.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1015470683;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_my_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSendmeCancelReceive();

  Future<List<String>> crateApiSimpleGetDebugLogs();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Stream<ReceiveProgress> crateApiSendmeStartReceive({
    required String ticketStr,
    required String tempDir,
    required String destinationDir,
  });

  Stream<SendProgress> crateApiSendmeStartSend({
    required String path,
    required String tempDir,
  });

  Future<void> crateApiSendmeStopSend();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSendmeCancelReceive() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSendmeCancelReceiveConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendmeCancelReceiveConstMeta =>
      const TaskConstMeta(debugName: "cancel_receive", argNames: []);

  @override
  Future<List<String>> crateApiSimpleGetDebugLogs() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetDebugLogsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetDebugLogsConstMeta =>
      const TaskConstMeta(debugName: "get_debug_logs", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Stream<ReceiveProgress> crateApiSendmeStartReceive({
    required String ticketStr,
    required String tempDir,
    required String destinationDir,
  }) {
    final sink = RustStreamSink<ReceiveProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(ticketStr, serializer);
            sse_encode_String(tempDir, serializer);
            sse_encode_String(destinationDir, serializer);
            sse_encode_StreamSink_receive_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 7,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSendmeStartReceiveConstMeta,
          argValues: [ticketStr, tempDir, destinationDir, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSendmeStartReceiveConstMeta => const TaskConstMeta(
    debugName: "start_receive",
    argNames: ["ticketStr", "tempDir", "destinationDir", "sink"],
  );

  @override
  Stream<SendProgress> crateApiSendmeStartSend({
    required String path,
    required String tempDir,
  }) {
    final sink = RustStreamSink<SendProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(path, serializer);
            sse_encode_String(tempDir, serializer);
            sse_encode_StreamSink_send_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 8,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSendmeStartSendConstMeta,
          argValues: [path, tempDir, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSendmeStartSendConstMeta => const TaskConstMeta(
    debugName: "start_send",
    argNames: ["path", "tempDir", "sink"],
  );

  @override
  Future<void> crateApiSendmeStopSend() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSendmeStopSendConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendmeStopSendConstMeta =>
      const TaskConstMeta(debugName: "stop_send", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<ReceiveProgress> dco_decode_StreamSink_receive_progress_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<SendProgress> dco_decode_StreamSink_send_progress_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ReceiveProgressReporter dco_decode_TraitDef_ReceiveProgressReporter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  SendProgressReporter dco_decode_TraitDef_SendProgressReporter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ReceiveProgress dco_decode_box_autoadd_receive_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_receive_progress(raw);
  }

  @protected
  SendProgress dco_decode_box_autoadd_send_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_send_progress(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  ReceiveProgress dco_decode_receive_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ReceiveProgress_Connecting();
      case 1:
        return ReceiveProgress_Connected();
      case 2:
        return ReceiveProgress_RetrievingMetadata();
      case 3:
        return ReceiveProgress_Downloading(
          bytesDownloaded: dco_decode_u_64(raw[1]),
          totalBytes: dco_decode_u_64(raw[2]),
          percentage: dco_decode_f_64(raw[3]),
        );
      case 4:
        return ReceiveProgress_DownloadDone(
          totalBytes: dco_decode_u_64(raw[1]),
        );
      case 5:
        return ReceiveProgress_Exporting(
          fileName: dco_decode_String(raw[1]),
          bytesExported: dco_decode_u_64(raw[2]),
          bytesTotal: dco_decode_u_64(raw[3]),
        );
      case 6:
        return ReceiveProgress_Finished(
          totalFiles: dco_decode_u_64(raw[1]),
          totalBytes: dco_decode_u_64(raw[2]),
        );
      case 7:
        return ReceiveProgress_Failed(error: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  SendProgress dco_decode_send_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return SendProgress_Importing(
          fileName: dco_decode_String(raw[1]),
          bytesDone: dco_decode_u_64(raw[2]),
          bytesTotal: dco_decode_u_64(raw[3]),
        );
      case 1:
        return SendProgress_ImportDone(totalSize: dco_decode_u_64(raw[1]));
      case 2:
        return SendProgress_StartingEndpoint();
      case 3:
        return SendProgress_Sharing(ticket: dco_decode_String(raw[1]));
      case 4:
        return SendProgress_Failed(error: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<ReceiveProgress> sse_decode_StreamSink_receive_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<SendProgress> sse_decode_StreamSink_send_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ReceiveProgress sse_decode_box_autoadd_receive_progress(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_receive_progress(deserializer));
  }

  @protected
  SendProgress sse_decode_box_autoadd_send_progress(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_send_progress(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  ReceiveProgress sse_decode_receive_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return ReceiveProgress_Connecting();
      case 1:
        return ReceiveProgress_Connected();
      case 2:
        return ReceiveProgress_RetrievingMetadata();
      case 3:
        var var_bytesDownloaded = sse_decode_u_64(deserializer);
        var var_totalBytes = sse_decode_u_64(deserializer);
        var var_percentage = sse_decode_f_64(deserializer);
        return ReceiveProgress_Downloading(
          bytesDownloaded: var_bytesDownloaded,
          totalBytes: var_totalBytes,
          percentage: var_percentage,
        );
      case 4:
        var var_totalBytes = sse_decode_u_64(deserializer);
        return ReceiveProgress_DownloadDone(totalBytes: var_totalBytes);
      case 5:
        var var_fileName = sse_decode_String(deserializer);
        var var_bytesExported = sse_decode_u_64(deserializer);
        var var_bytesTotal = sse_decode_u_64(deserializer);
        return ReceiveProgress_Exporting(
          fileName: var_fileName,
          bytesExported: var_bytesExported,
          bytesTotal: var_bytesTotal,
        );
      case 6:
        var var_totalFiles = sse_decode_u_64(deserializer);
        var var_totalBytes = sse_decode_u_64(deserializer);
        return ReceiveProgress_Finished(
          totalFiles: var_totalFiles,
          totalBytes: var_totalBytes,
        );
      case 7:
        var var_error = sse_decode_String(deserializer);
        return ReceiveProgress_Failed(error: var_error);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  SendProgress sse_decode_send_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_fileName = sse_decode_String(deserializer);
        var var_bytesDone = sse_decode_u_64(deserializer);
        var var_bytesTotal = sse_decode_u_64(deserializer);
        return SendProgress_Importing(
          fileName: var_fileName,
          bytesDone: var_bytesDone,
          bytesTotal: var_bytesTotal,
        );
      case 1:
        var var_totalSize = sse_decode_u_64(deserializer);
        return SendProgress_ImportDone(totalSize: var_totalSize);
      case 2:
        return SendProgress_StartingEndpoint();
      case 3:
        var var_ticket = sse_decode_String(deserializer);
        return SendProgress_Sharing(ticket: var_ticket);
      case 4:
        var var_error = sse_decode_String(deserializer);
        return SendProgress_Failed(error: var_error);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_receive_progress_Sse(
    RustStreamSink<ReceiveProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_receive_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_send_progress_Sse(
    RustStreamSink<SendProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_send_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_receive_progress(
    ReceiveProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_receive_progress(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_send_progress(
    SendProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_send_progress(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_receive_progress(
    ReceiveProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ReceiveProgress_Connecting():
        sse_encode_i_32(0, serializer);
      case ReceiveProgress_Connected():
        sse_encode_i_32(1, serializer);
      case ReceiveProgress_RetrievingMetadata():
        sse_encode_i_32(2, serializer);
      case ReceiveProgress_Downloading(
        bytesDownloaded: final bytesDownloaded,
        totalBytes: final totalBytes,
        percentage: final percentage,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_u_64(bytesDownloaded, serializer);
        sse_encode_u_64(totalBytes, serializer);
        sse_encode_f_64(percentage, serializer);
      case ReceiveProgress_DownloadDone(totalBytes: final totalBytes):
        sse_encode_i_32(4, serializer);
        sse_encode_u_64(totalBytes, serializer);
      case ReceiveProgress_Exporting(
        fileName: final fileName,
        bytesExported: final bytesExported,
        bytesTotal: final bytesTotal,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_String(fileName, serializer);
        sse_encode_u_64(bytesExported, serializer);
        sse_encode_u_64(bytesTotal, serializer);
      case ReceiveProgress_Finished(
        totalFiles: final totalFiles,
        totalBytes: final totalBytes,
      ):
        sse_encode_i_32(6, serializer);
        sse_encode_u_64(totalFiles, serializer);
        sse_encode_u_64(totalBytes, serializer);
      case ReceiveProgress_Failed(error: final error):
        sse_encode_i_32(7, serializer);
        sse_encode_String(error, serializer);
    }
  }

  @protected
  void sse_encode_send_progress(SendProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case SendProgress_Importing(
        fileName: final fileName,
        bytesDone: final bytesDone,
        bytesTotal: final bytesTotal,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(fileName, serializer);
        sse_encode_u_64(bytesDone, serializer);
        sse_encode_u_64(bytesTotal, serializer);
      case SendProgress_ImportDone(totalSize: final totalSize):
        sse_encode_i_32(1, serializer);
        sse_encode_u_64(totalSize, serializer);
      case SendProgress_StartingEndpoint():
        sse_encode_i_32(2, serializer);
      case SendProgress_Sharing(ticket: final ticket):
        sse_encode_i_32(3, serializer);
        sse_encode_String(ticket, serializer);
      case SendProgress_Failed(error: final error):
        sse_encode_i_32(4, serializer);
        sse_encode_String(error, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
