// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'sendme.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `canonicalized_path_to_string`, `export_with_progress`, `get_export_path`, `import_with_progress`, `start_receive_inner`, `start_send_inner`, `validate_path_component`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ReceiveSession`, `SendSession`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `report`, `report`

/// Start sharing a file or directory over Iroh P2P.
///
/// Streams [`SendProgress`] updates to Dart via `sink`.
Stream<SendProgress> startSend({
  required String path,
  required String tempDir,
}) =>
    RustLib.instance.api.crateApiSendmeStartSend(path: path, tempDir: tempDir);

/// Stop an active send session, shutdown the router, and reclaim temporary blob storage.
Future<void> stopSend() => RustLib.instance.api.crateApiSendmeStopSend();

/// Start receiving (downloading) data using a Sendme ticket string.
///
/// Streams [`ReceiveProgress`] updates to Dart via `sink`.
Stream<ReceiveProgress> startReceive({
  required String ticketStr,
  required String tempDir,
  required String destinationDir,
}) => RustLib.instance.api.crateApiSendmeStartReceive(
  ticketStr: ticketStr,
  tempDir: tempDir,
  destinationDir: destinationDir,
);

/// Cancel an active receive session and abort in-flight transfers.
Future<void> cancelReceive() =>
    RustLib.instance.api.crateApiSendmeCancelReceive();

abstract class ReceiveProgressReporter {
  Future<void> report({required ReceiveProgress progress});
}

abstract class SendProgressReporter {
  Future<void> report({required SendProgress progress});
}

@freezed
sealed class ReceiveProgress with _$ReceiveProgress {
  const ReceiveProgress._();

  /// Attempting to establish a connection to the peer via relay or direct QUIC.
  const factory ReceiveProgress.connecting() = ReceiveProgress_Connecting;

  /// Successfully established a QUIC connection with the remote peer.
  const factory ReceiveProgress.connected() = ReceiveProgress_Connected;

  /// Retrieving the hash sequence and metadata for the collection.
  const factory ReceiveProgress.retrievingMetadata() =
      ReceiveProgress_RetrievingMetadata;

  /// Downloading blob data over the network.
  const factory ReceiveProgress.downloading({
    required BigInt bytesDownloaded,
    required BigInt totalBytes,
    required double percentage,
  }) = ReceiveProgress_Downloading;

  /// All raw blob data has finished downloading into the local store.
  const factory ReceiveProgress.downloadDone({required BigInt totalBytes}) =
      ReceiveProgress_DownloadDone;

  /// Exporting a specific file from the blob store onto the filesystem.
  const factory ReceiveProgress.exporting({
    required String fileName,
    required BigInt bytesExported,
    required BigInt bytesTotal,
  }) = ReceiveProgress_Exporting;

  /// The entire transfer and export operation has completed successfully.
  const factory ReceiveProgress.finished({
    required BigInt totalFiles,
    required BigInt totalBytes,
    required List<String> exportedPaths,
  }) = ReceiveProgress_Finished;

  /// A fatal error or user cancellation occurred during the receive workflow.
  const factory ReceiveProgress.failed({required String error}) =
      ReceiveProgress_Failed;
}

@freezed
sealed class SendProgress with _$SendProgress {
  const SendProgress._();

  /// Incremental progress when hashing and importing a file into the local blob store.
  const factory SendProgress.importing({
    required String fileName,
    required BigInt bytesDone,
    required BigInt bytesTotal,
  }) = SendProgress_Importing;

  /// All files have been imported and packed into an Iroh collection.
  const factory SendProgress.importDone({required BigInt totalSize}) =
      SendProgress_ImportDone;

  /// Binding the local QUIC endpoint and connecting to the relay network.
  const factory SendProgress.startingEndpoint() = SendProgress_StartingEndpoint;

  /// The ticket is ready and the node is actively serving blobs.
  const factory SendProgress.sharing({required String ticket}) =
      SendProgress_Sharing;

  /// A fatal error occurred during the send workflow.
  const factory SendProgress.failed({required String error}) =
      SendProgress_Failed;
}
